// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLiaQ3Fs8donWDzqoA-n7FaKCaWfM8sTc',
    appId: '1:769666598578:web:6846e483783620a33cebab',
    messagingSenderId: '769666598578',
    projectId: 'sobhanath-dairy-farm',
    authDomain: 'sobhanath-dairy-farm.firebaseapp.com',
    storageBucket: 'sobhanath-dairy-farm.firebasestorage.app',
    measurementId: 'G-9Q8G3V6WXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhbrGhBRy7cT-dlQdrWezDgHqx25eZBE0',
    appId: '1:769666598578:android:c1d3f5ca63fecccd3cebab',
    messagingSenderId: '769666598578',
    projectId: 'sobhanath-dairy-farm',
    storageBucket: 'sobhanath-dairy-farm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CAJQEbmNa2cI6IzMuU12N8lHUUyDUts',
    appId: '1:769666598578:ios:e98a0a20b14c83e43cebab',
    messagingSenderId: '769666598578',
    projectId: 'sobhanath-dairy-farm',
    storageBucket: 'sobhanath-dairy-farm.firebasestorage.app',
    iosBundleId: 'com.example.sobhanathDairyFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9CAJQEbmNa2cI6IzMuU12N8lHUUyDUts',
    appId: '1:769666598578:ios:e98a0a20b14c83e43cebab',
    messagingSenderId: '769666598578',
    projectId: 'sobhanath-dairy-farm',
    storageBucket: 'sobhanath-dairy-farm.firebasestorage.app',
    iosBundleId: 'com.example.sobhanathDairyFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLiaQ3Fs8donWDzqoA-n7FaKCaWfM8sTc',
    appId: '1:769666598578:web:7a79afc6d899d41f3cebab',
    messagingSenderId: '769666598578',
    projectId: 'sobhanath-dairy-farm',
    authDomain: 'sobhanath-dairy-farm.firebaseapp.com',
    storageBucket: 'sobhanath-dairy-farm.firebasestorage.app',
    measurementId: 'G-TRJG2FTYCQ',
  );
}
